version: '3'

services:
    db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=testpass
            - POSTGRES_DB=challenge_db
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./db/sql:/docker-entrypoint-initdb.d
        expose:
            - "5432"

    backend:
        build: backend-node
        command: pm2-dev app.js
        links:
            - db
        ports:
            - "18000:8000"
        volumes:
            - ./backend-node:/src/app
        depends_on:
            - db

    fullstack:
        build: frontend-react
        links:
            - backend
        ports:
            - "13000:3000"

volumes:
    db-data:
